version: "3"
services:
  python:
    build:
      context: python
      dockerfile: Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - BROKER_PORT=${BROKER_PORT}
      - BROADCAST_SPACE=${BROADCAST_SPACE}
    volumes:
      - ./python:/app
    networks:
      - my-network
    depends_on:
      - mqtt

  mqtt:
    image: eclipse-mosquitto
    networks:
      - my-network
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 2000:1883

networks:
  my-network:
    driver: bridge
