version: "3"
services:
  sample-data:
    build:
      context: sample-data
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_URL=${INFLUXDB_URL}
    volumes:
      - ./sample-data:/app
    networks:
      - my-network
    depends_on:
      - influxdb
  python:
    build:
      context: python
      dockerfile: Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - BROKER_PORT=${BROKER_PORT}
      - BROADCAST_SPACE=${BROADCAST_SPACE}
    volumes:
      - ./python:/app
    networks:
      - my-network
    depends_on:
      - mqtt
  mqtt:
    image: eclipse-mosquitto
    networks:
      - my-network
    volumes:
      - ./mosquitto:/mosquitto
    ports:
      - 2000:1883
  influxdb:
    image: influxdb
    networks:
      - my-network
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
  nodejs:
    build:
      context: nodejs
      dockerfile: Dockerfile
    ports:
      - "${NODEJS_PORT}:${NODEJS_PORT}"
    volumes:
      - ./nodejs:/app
    environment:
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - BROKER_PORT=${BROKER_PORT}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - NODEJS_PORT=${NODEJS_PORT}
    networks:
      - my-network
    depends_on:
      - influxdb
      - mqtt
  dashboard:
    build:
      context: dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./dashboard:/app
    environment:
      - REACT_APP_NODEJS_PORT=${NODEJS_PORT}
    networks:
      - my-network
    depends_on:
      - influxdb
      - mqtt
      - nodejs
volumes:
  influxdb_data:
  node_red_data:

networks:
  my-network:
    driver: bridge
